"""file pin owner index

Revision ID: 8edf69c47884
Revises: eef5f95853bf
Create Date: 2023-01-25 00:55:29.953070

"""
from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision = "8edf69c47884"
down_revision = "eef5f95853bf"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(
        "ix_file_pins_owner",
        "file_pins",
        ["owner"],
        unique=False,
        postgresql_where=sa.text("owner IS NOT NULL"),
        postgresql_using="HASH",
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(
        "ix_file_pins_owner",
        table_name="file_pins",
        postgresql_where=sa.text("owner IS NOT NULL"),
        postgresql_using="HASH",
    )
    # ### end Alembic commands ###
