"""Add sender_address column and index

Revision ID: a18051177947
Revises: dfc5f95e4fe6
Create Date: 2025-07-29 14:28:52.871778

"""
from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision = 'dfc5f95e4fe6'
down_revision = '8ece21fbeb47'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('pending_messages', sa.Column('content_address', sa.String(), sa.Computed("content->>'address'", persisted=True), nullable=True))
    op.create_index(op.f('ix_pending_messages_content_address'), 'pending_messages', ['content_address'], unique=False)
    op.create_index('ix_pending_messages_content_address_attempt', 'pending_messages', ['content_address', 'next_attempt'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    op.drop_index('ix_pending_messages_content_address_attempt', table_name='pending_messages')
    op.drop_index(op.f('ix_pending_messages_content_address'), table_name='pending_messages')
    op.drop_column('pending_messages', 'content_address')
