"""Add pending_message index on time field

Revision ID: 35a67ccc4451
Revises: 8ece21fbeb47
Create Date: 2025-09-04 08:29:17.540060

"""
from alembic import op

# revision identifiers, used by Alembic.
revision = '35a67ccc4451'
down_revision = '8ece21fbeb47'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_pending_messages_time'), 'pending_messages', ['time'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_pending_messages_time'), table_name='pending_messages')
    # ### end Alembic commands ###
