"""permissions v2

Revision ID: 7cd87cef231f
Revises: f9fa39b6bdef
Create Date: 2023-06-23 11:44:56.150233

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7cd87cef231f'
down_revision = 'f9fa39b6bdef'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('permissions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('owner', sa.String(), nullable=False),
    sa.Column('address', sa.String(), nullable=False),
    sa.Column('type', sa.String(), nullable=False),
    sa.Column('valid_from', sa.TIMESTAMP(timezone=True), nullable=True),
    sa.Column('valid_until', sa.TIMESTAMP(timezone=True), nullable=True),
    sa.Column('channel', sa.String(), nullable=True),
    sa.Column('create', sa.Boolean(), nullable=False),
    sa.Column('update', sa.Boolean(), nullable=False),
    sa.Column('delete', sa.Boolean(), nullable=False),
    sa.Column('ref', sa.String(), nullable=True),
    sa.Column('addresses', sa.ARRAY(sa.String()), nullable=True),
    sa.Column('key', sa.String(), nullable=True),
    sa.Column('post_type', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_owner_address', 'permissions', ['owner', 'address'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_owner_address', table_name='permissions')
    op.drop_table('permissions')
    # ### end Alembic commands ###
