# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

from . import aleph_p2p_pb2 as aleph__p2p__pb2

GRPC_GENERATED_VERSION = '1.81.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in aleph_p2p_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class AlephP2PStub:
    """Control and pubsub API of the aleph.im P2P service.
    Errors are returned as gRPC statuses:
    - Dial: NOT_FOUND (peer unreachable), FAILED_PRECONDITION (peer id mismatch),
    INVALID_ARGUMENT (bad peer id / multiaddr), INTERNAL (other).
    - Publish: INVALID_ARGUMENT (bad topic), INTERNAL (gossipsub error).
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.Identify = channel.unary_unary(
                '/aleph.p2p.v1.AlephP2P/Identify',
                request_serializer=aleph__p2p__pb2.IdentifyRequest.SerializeToString,
                response_deserializer=aleph__p2p__pb2.NodeInfo.FromString,
                _registered_method=True)
        self.Dial = channel.unary_unary(
                '/aleph.p2p.v1.AlephP2P/Dial',
                request_serializer=aleph__p2p__pb2.DialRequest.SerializeToString,
                response_deserializer=aleph__p2p__pb2.DialResponse.FromString,
                _registered_method=True)
        self.Publish = channel.unary_unary(
                '/aleph.p2p.v1.AlephP2P/Publish',
                request_serializer=aleph__p2p__pb2.PublishRequest.SerializeToString,
                response_deserializer=aleph__p2p__pb2.PublishResponse.FromString,
                _registered_method=True)
        self.Subscribe = channel.unary_stream(
                '/aleph.p2p.v1.AlephP2P/Subscribe',
                request_serializer=aleph__p2p__pb2.SubscribeRequest.SerializeToString,
                response_deserializer=aleph__p2p__pb2.PubsubEnvelope.FromString,
                _registered_method=True)
        self.SetPreferredPeers = channel.unary_unary(
                '/aleph.p2p.v1.AlephP2P/SetPreferredPeers',
                request_serializer=aleph__p2p__pb2.PreferredPeerSet.SerializeToString,
                response_deserializer=aleph__p2p__pb2.SetPreferredPeersResult.FromString,
                _registered_method=True)
        self.GetPeers = channel.unary_unary(
                '/aleph.p2p.v1.AlephP2P/GetPeers',
                request_serializer=aleph__p2p__pb2.GetPeersRequest.SerializeToString,
                response_deserializer=aleph__p2p__pb2.PeerList.FromString,
                _registered_method=True)


class AlephP2PServicer:
    """Control and pubsub API of the aleph.im P2P service.
    Errors are returned as gRPC statuses:
    - Dial: NOT_FOUND (peer unreachable), FAILED_PRECONDITION (peer id mismatch),
    INVALID_ARGUMENT (bad peer id / multiaddr), INTERNAL (other).
    - Publish: INVALID_ARGUMENT (bad topic), INTERNAL (gossipsub error).
    """

    def Identify(self, request, context):
        """Local node identity and addresses.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Dial(self, request, context):
        """Dial a remote peer. Returns once the connection is established or failed.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Publish(self, request, context):
        """Publish a message on a gossipsub topic. With echo=true, the message is
        also delivered to local Subscribe streams for this topic.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Subscribe(self, request, context):
        """Subscribe to a gossipsub topic. Server stream of received messages.
        The per-subscriber buffer is bounded; on overflow the oldest messages
        are dropped and counted in metrics.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def SetPreferredPeers(self, request, context):
        """Replace the full set of preferred peers (registry-backed CCNs).
        Preferred peers are protected from pruning and receive a gossipsub
        application score bonus. The set is capped server-side.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetPeers(self, request, context):
        """List currently connected peers.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_AlephP2PServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'Identify': grpc.unary_unary_rpc_method_handler(
                    servicer.Identify,
                    request_deserializer=aleph__p2p__pb2.IdentifyRequest.FromString,
                    response_serializer=aleph__p2p__pb2.NodeInfo.SerializeToString,
            ),
            'Dial': grpc.unary_unary_rpc_method_handler(
                    servicer.Dial,
                    request_deserializer=aleph__p2p__pb2.DialRequest.FromString,
                    response_serializer=aleph__p2p__pb2.DialResponse.SerializeToString,
            ),
            'Publish': grpc.unary_unary_rpc_method_handler(
                    servicer.Publish,
                    request_deserializer=aleph__p2p__pb2.PublishRequest.FromString,
                    response_serializer=aleph__p2p__pb2.PublishResponse.SerializeToString,
            ),
            'Subscribe': grpc.unary_stream_rpc_method_handler(
                    servicer.Subscribe,
                    request_deserializer=aleph__p2p__pb2.SubscribeRequest.FromString,
                    response_serializer=aleph__p2p__pb2.PubsubEnvelope.SerializeToString,
            ),
            'SetPreferredPeers': grpc.unary_unary_rpc_method_handler(
                    servicer.SetPreferredPeers,
                    request_deserializer=aleph__p2p__pb2.PreferredPeerSet.FromString,
                    response_serializer=aleph__p2p__pb2.SetPreferredPeersResult.SerializeToString,
            ),
            'GetPeers': grpc.unary_unary_rpc_method_handler(
                    servicer.GetPeers,
                    request_deserializer=aleph__p2p__pb2.GetPeersRequest.FromString,
                    response_serializer=aleph__p2p__pb2.PeerList.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'aleph.p2p.v1.AlephP2P', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('aleph.p2p.v1.AlephP2P', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class AlephP2P:
    """Control and pubsub API of the aleph.im P2P service.
    Errors are returned as gRPC statuses:
    - Dial: NOT_FOUND (peer unreachable), FAILED_PRECONDITION (peer id mismatch),
    INVALID_ARGUMENT (bad peer id / multiaddr), INTERNAL (other).
    - Publish: INVALID_ARGUMENT (bad topic), INTERNAL (gossipsub error).
    """

    @staticmethod
    def Identify(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/aleph.p2p.v1.AlephP2P/Identify',
            aleph__p2p__pb2.IdentifyRequest.SerializeToString,
            aleph__p2p__pb2.NodeInfo.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Dial(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/aleph.p2p.v1.AlephP2P/Dial',
            aleph__p2p__pb2.DialRequest.SerializeToString,
            aleph__p2p__pb2.DialResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Publish(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/aleph.p2p.v1.AlephP2P/Publish',
            aleph__p2p__pb2.PublishRequest.SerializeToString,
            aleph__p2p__pb2.PublishResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Subscribe(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_stream(
            request,
            target,
            '/aleph.p2p.v1.AlephP2P/Subscribe',
            aleph__p2p__pb2.SubscribeRequest.SerializeToString,
            aleph__p2p__pb2.PubsubEnvelope.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def SetPreferredPeers(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/aleph.p2p.v1.AlephP2P/SetPreferredPeers',
            aleph__p2p__pb2.PreferredPeerSet.SerializeToString,
            aleph__p2p__pb2.SetPreferredPeersResult.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetPeers(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/aleph.p2p.v1.AlephP2P/GetPeers',
            aleph__p2p__pb2.GetPeersRequest.SerializeToString,
            aleph__p2p__pb2.PeerList.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
