{
 "title": "Sync",
 "time": { "from": "now-30m", "to": "now" },
 "refresh": "10s",
 "panels": [
  {
   "title": "Mem free",
   "type": "graph",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    { "expr": "node_memory_MemFree_bytes", "legendFormat": "MemFree total" },
    { "expr": "node_memory_MemFree_bytes", "legendFormat": "MemFree details" }
   ]
  },
  {
   "title": "CPU Load",
   "type": "graph",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "node_load1" },
    { "expr": "node_load5" },
    { "expr": "node_load15" }
   ]
  },
  {
   "title": "Messages stored",
   "type": "graph",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 6 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "pyaleph_status_sync_messages_total"
    }
   ]
  },
  {
   "title": "Messages remaining",
   "type": "graph",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 6 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "pyaleph_status_sync_messages_remaining_total"
    }
   ]
  },
  {
   "title": "Pending Msg/Txs",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 12 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "pyaleph_status_sync_pending_messages_total",
     "legendFormat": "Messages"
    },
    {
     "expr": "pyaleph_status_sync_pending_txs_total",
     "legendFormat": "Txs"
    }
   ]
  },
  {
   "title": "ETH remaining",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 12 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "-delta(pyaleph_status_sync_messages_remaining_total[1m])",
     "legendFormat": "eth per minute"
    },
    {
     "expr": "pyaleph_status_sync_messages_remaining_total",
     "legendFormat": "eth remaining"
    }
   ]
  },
  {
   "title": "job_seen_ids",
   "type": "graph",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 19 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "pyaleph_processing_pending_messages_seen_ids_total"
    }
   ]
  },
  {
   "title": "gtasks",
   "type": "graph",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 19 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "pyaleph_processing_pending_messages_gtasks_total"
    }
   ]
  },
  {
   "title": "messages_actions",
   "type": "graph",
   "gridPos": { "h": 5, "w": 12, "x": 0, "y": 25 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "pyaleph_processing_pending_messages_messages_actions_total"
    }
   ]
  },
  {
   "title": "tasks",
   "type": "graph",
   "gridPos": { "h": 5, "w": 12, "x": 12, "y": 25 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "pyaleph_processing_pending_messages_tasks_total"
    }
   ]
  },
  {
   "title": "job_actions ",
   "type": "graph",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 30 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "pyaleph_processing_pending_messages_action_total"
    }
   ]
  },
  {
   "title": "counter i",
   "type": "graph",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 30 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "pyaleph_processing_pending_messages_i_total"
    }
   ]
  },
  {
   "title": "Peers",
   "type": "graph",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 36 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "pyaleph_status_peers_total - 2" }
   ]
  },
  {
   "title": "counter j",
   "type": "graph",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 36 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "pyaleph_processing_pending_messages_j_total"
    }
   ]
  }
 ]
}