{
 "title": "Sync",
 "time": { "from": "now-3h", "to": "now" },
 "panels": [
  {
   "title": "Mem free",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "node_memory_MemFree_bytes" }
   ]
  },
  {
   "title": "CPU Load",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "node_load1" },
    { "expr": "node_load5" },
    { "expr": "node_load15" }
   ]
  },
  {
   "title": "Messages stored",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "pyaleph_status_sync_messages_total"
    }
   ]
  },
  {
   "title": "Messages remaining",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "pyaleph_status_sync_messages_remaining_total"
    }
   ]
  },
  {
   "title": "Pending Msg/Txs",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 16 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "pyaleph_status_sync_pending_messages_total",
     "legendFormat": "Messages"
    },
    {
     "expr": "pyaleph_status_sync_pending_txs_total",
     "legendFormat": "Txs"
    }
   ]
  },
  {
   "title": "ETH remaining",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 16 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "pyaleph_status_chain_eth_height_remaining_total"
    }
   ]
  },
  {
   "title": "job_seen_ids",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 24 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "pyaleph_retry_messages_job_seen_ids"
    }
   ]
  },
  {
   "title": "tasks",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 24 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "pyaleph_retry_messages_job_tasks"
    }
   ]
  },
  {
   "title": "gtasks",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 32 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "pyaleph_retry_messages_job_gtasks"
    }
   ]
  },
  {
   "title": "job_actions ",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 32 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "pyaleph_retry_messages_job_actions "
    }
   ]
  },
  {
   "title": "messages_actions",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 40 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "pyaleph_retry_messages_job_messages_actions"
    }
   ]
  }
 ]
}