{
 "title": "Aleph Node Metrics",
 "time": { "from": "now-6h", "to": "now" },
 "refresh": "10s",
 "panels": [
  {
   "title": "processing_pending_messages_i",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "pyaleph_processing_pending_messages_i_total"
    }
   ]
  },
  {
   "title": "processing_pending_messages_j",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "pyaleph_processing_pending_messages_j_total"
    }
   ]
  },
  {
   "title": "processing_pending_messages_messages_actions",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "pyaleph_processing_pending_messages_messages_actions_total"
    }
   ]
  },
  {
   "title": "processing_pending_messages_action",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "pyaleph_processing_pending_messages_action_total"
    }
   ]
  },
  {
   "title": "processing_pending_messages_tasks",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 16 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "pyaleph_processing_pending_messages_tasks_total"
    }
   ]
  },
  {
   "title": "processing_pending_messages_gtasks",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 16 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "pyaleph_processing_pending_messages_gtasks_total"
    }
   ]
  },
  {
   "title": "processing_pending_messages_seen_ids",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 24 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "pyaleph_processing_pending_messages_seen_ids_total"
    }
   ]
  },
  {
   "title": "ETH Sync",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 24 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "pyaleph_status_chain_eth_height_remaining_total"
    }
   ]
  },
  {
   "title": "Pending Messages",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 32 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "pyaleph_status_sync_pending_messages_total"
    }
   ]
  },
  {
   "title": "status_sync_messages",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 32 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "pyaleph_status_sync_messages_total"
    }
   ]
  },
  {
   "title": "Peers Total",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 40 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "pyaleph_status_peers_total" }
   ]
  }
 ]
}